### ISSUE TITLE
Highlight search query

### ISSUE THREAD

**Issue by mafsi** [mrjackphil/obsidian-text-expand#31]
Hi,
In
```
` ` ` expander
SEARCH_QUERY
-[[$lines:5]]
` ` `
```

Can we get query hightlighted? (`==SEARCH_QUERY==`)  It is easier to spot. Thanks!

**Comment by mrjackphil** [comment]
Hi, @mafsi. 

We can use a custom CSS snippet to achieve that in preview mode. It'll be a little bit more challenging to achieve the same in source mode. 

```css 
code.is-loaded.language-expander::first-line  {
  background: var(--text-highlight-bg);
}
```
