### ISSUE TITLE
How can I hide the search request in preview mode?

### ISSUE THREAD

**Issue by jorgekoronis** [mrjackphil/obsidian-text-expand#56]
Hello
How can I hide the search request in preview mode?
I just want to see the output of the search request in preview mode.
Thanks

**Comment by mrjackphil** [comment]
Hi, @jorgekoronis . You can use css snippet, something like this:

```css
.language-expander {
    display: none;
}
```
